site_name: Arkeo Multichannel API Documentation (v0.5.0)

theme:
  name: material
  features:
    - navigation.expand
    - navigation.sections
    - navigation.instant
    - navigation.top
    - search.highlight
    - search.suggest
    - content.code.annotate
    - content.code.copy
    - content.icons


markdown_extensions:
  - toc:
      permalink: true
  - tables
  - pymdownx.highlight:
      anchor_linenums: false
      linenums: false
      guess_lang: false
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - attr_list
  - md_in_html
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg

nav:
  - Introduction: index.md
  - Commands:
      - Overview: commands/index.md
      - Device Commands: commands/device.md
      - Sensor Commands: commands/sensors.md
      - Environment Commands: commands/environments.md
      - Day-Night Commands: commands/day-night.md
  - Configuration JSONs:
    - Settings: jsons/settings-json.md
    - State: jsons/state-json.md
    - Sensors: jsons/sensor-json.md
    - Enviroments: jsons/environment-json.md
  - Examples:
    - Python: examples/python.md
  - Changelog: changelog.md

extra_javascript:
  - https://cdn.jsdelivr.net/npm/katex@0.16.9/dist/katex.min.js
  - https://cdn.jsdelivr.net/npm/katex@0.16.9/dist/contrib/auto-render.min.js
  - js/katex-init.js

extra_css:
  - https://cdn.jsdelivr.net/npm/katex@0.16.9/dist/katex.min.css
  - assets/stylesheets/extra.css
